plugins {
    id 'java'
}

group = 'com.tup.programacion3'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    //lombok
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
    // Implementación de JPA (Hibernate)
    implementation 'org.hibernate.orm:hibernate-core:6.4.4.Final'
    // Driver de la base de datos H2
    runtimeOnly 'com.h2database:h2:2.2.224'
}

test {
    useJUnitPlatform()
}